# Generated by Django 2.2.8 on 2020-04-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200426_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('query', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
